In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 6, 7, 8, 9, 10]).reshape((-1, 1))
y = np.array([70, 60, 50, 40, 30, 20])

In [9]:
>>> print(x)
[[5],
 [6],
 [7],
 [8],
 [9],
 [10]]
>>> print(y)
[ 70, 60, 50, 40, 30, 20]

[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[70 60 50 40 30 20]


[70, 60, 50, 40, 30, 20]

In [16]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
>>> r_sq = model.score(x, y)
>>> print('coefficient of determination:', r_sq)

coefficient of determination: 1.0


In [18]:
>>> print('intercept:', model.intercept_)
intercept: 5.633333333333329
>>> print('slope:', model.coef_)

intercept: 120.00000000000001
slope: [-10.]


In [20]:
>>> new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
>>> print('intercept:', new_model.intercept_)
>>> print('slope:', new_model.coef_)

intercept: [120.]
slope: [[-10.]]


In [21]:
>>> y_pred = model.predict(x)
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[70. 60. 50. 40. 30. 20.]


In [22]:
>>> y_pred = model.intercept_ + model.coef_ * x
>>> print('predicted response:', y_pred, sep='\n')

predicted response:
[[70.]
 [60.]
 [50.]
 [40.]
 [30.]
 [20.]]


In [24]:
>>> x_new = np.arange(10).reshape((-1, 1))
>>> print(x_new)
>>> y_new = model.predict(x_new)
>>> print(y_new)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[120. 110. 100.  90.  80.  70.  60.  50.  40.  30.]


In [1]:
import PyPDF2

In [4]:
pdfFileObj = open('Wss1 figures.pdf', 'rb') 

FileNotFoundError: [Errno 2] No such file or directory: 'Wss1 figures.pdf'

In [7]:
# importing required modules 
import PyPDF2 

# creating a pdf file object 
pdfFileObj = open('Rnf169 fl.pdf', 'rb') 

# creating a pdf reader object 
pdfReader = PyPDF2.PdfFileReader(pdfFileObj) 

# printing number of pages in pdf file 
print(pdfReader.numPages) 

# creating a page object 
pageObj = pdfReader.getPage(0) 

# extracting text from page 
print(pageObj.extractText()) 

# closing the pdf file object 
pdfFileObj.close() 


1
A
T
G
G
C
G
G
C
T
G
C
A
G
G
T
C
C
G
A
G
T
A
C
T
C
G
G
G
C
C
T
C
T
T
C
C
G
C
G
G
C
G
G
C
A
G
C
A
G
C
C
G
C
T
C
T
G
A
G
T
C
G
G
C
G
G
G
G
C
C
G
G
C
G
G
G
G
C
C
G
C
T
G
T
G
A
C
G
A
G
A
C
G
G
C
G
G
C
A
G
C
T
A
A
G
A
C
T
G
G
G
G
C
C
C
C
A
G
G
C
C
C
G
G
C
T
T
C
T
G
G
A
C
C
T
T
C
G
C
T
G
T
T
G
G
T
G
T
T
G
T
C
G
C
C
G
C
C
G
T
T
G
C
T
G
C
A
G
C
C
G
C
C
G
C
T
G
C
C
G
C
C
G
C
G
G
C
C
G
G
A
G
G
A
A
T
C
G
G
G
C
T
G
C
G
C
C
G
G
G
T
G
C
C
T
G
G
A
G
C
C
C
C
C
C
G
G
A
G
A
A
G
C
A
G
C
G
G
C
C
C
T
G
C
C
G
T
G
C
G
G
C
C
A
C
T
C
G
C
T
T
T
G
C
C
G
A
G
G
C
T
G
C
G
C
C
C
A
A
C
G
C
G
C
C
G
C
C
G
A
C
G
C
G
G
C
G
G
G
C
C
C
G
G
G
T
T
G
C
C
C
T
C
G
C
T
G
C
C
G
C
G
C
C
C
G
C
G
G
C
C
C
A
G
G
C
T
G
G
G
C
C
C
G
C
C
G
T
C
G
G
G
C
C
C
G
C
G
A
C
G
A
C
G
G
C
C
A
G
G
C
C
G
A
C
T
C
A
G
A
G
G
T
G
C
T
G
G
G
C
G
A
G
T
G
C
G
C
C
C
G
C
C
G
C
A
G
C
C
A
A
C
C
C
G
A
G
C
G
C
T
G
C
C
G
C
C
C
G
C
G
C
C
G
G
G
A
C
G
G
G
G
G
C
G
C
G
G
C
T
G
C
C
G
C
G
G
G
G
C
C
C
A
G
G
C
C
A
G
A
G
C
A
G
G
A
G
C
C
G
C
G
T
G
C
C
G
C
G
C
C
T
G
C
G
G
A
G
C
